Repository nextcloud/openapi-extractor, pull requests merged in 2024-02, with the labels that each got.

#93 chore: update workflows from templates
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/pr-feedback.yml
Labels: automated, dependencies, 3. to review

#73 feat(routing): Support new Route attribute
  generate-spec
  src/Route.php
  tests/lib/Controller/RoutingController.php
  tests/openapi-administration.json
  tests/openapi-full.json
Labels: enhancement

#97 fix: Load controllers in a deterministic order
  generate-spec
Labels: bug
